# Generated by Django 4.2.16 on 2024-10-27 01:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('intro', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=255)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DinnerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('dinner_coordinator', models.CharField(max_length=255)),
                ('date', models.DateField(verbose_name='event date')),
                ('food', wagtail.fields.StreamField([('pickup', 0), ('recipie', 1), ('todos', 1), ('images', 2)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'add details about the pickup food in the morning', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'add details about the dinner guests', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False})})),
                ('body', wagtail.fields.StreamField([('playbook', 0), ('donations', 1), ('guests', 1), ('images', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'playbook'}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
